name: Shell Script
on: 
  push:
    branches:
    - 'feature1/**'
jobs:
  run-shell-command1:
    runs-on: ubuntu-latest
    steps:
      - name: echo command
        shell: bash
        run: echo "First Hello World"
      - name: multi echo command
        shell: bash
        run: |
          echo "First Hello World 1"
          echo "First Hello World 2"
          echo "First Hello World 3"
  run-shell-command2:
    runs-on: ubuntu-latest
    needs: ["run-shell-command1"]
    steps:
      - name: echo command
        shell: bash
        run: echo "Second Hello World"
      - name: multi echo command
        shell: bash
        run: |
          echo "Second Hello World 1"
          echo "Second Hello World 2"
          echo "Second Hello World 3"
      - name: echo command git
        shell: bash
        run: echo "${{ github }}"
      